name: Rclone Automation

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 9,21 * * *' # Runs at 9:00 AM and 9:00 PM

jobs:
  rclone-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up rclone
        run: |
          echo "Installing rclone..."
          sudo apt-get update && sudo apt-get install -y rclone wget

      - name: Download rclone config file
        run: |
          echo "Downloading rclone config..."
          wget -q -O $HOME/rclone.conf "${{ secrets.RCLONE_CONFIG_URL }}"
          if [ $? -eq 0 ]; then
            echo "Rclone config downloaded successfully."
          else
            echo "Failed to download rclone config!" >&2
            exit 1
          fi

      - name: Rclone simultaneous operations
        run: |
          echo "Starting rclone operations..."
          rclone --config=$HOME/rclone.conf move ftp2:upload upload2: --transfers=2 --checkers=8 --stats=120s --verbose --dropbox-chunk-size 128m --order-by size,desc & \
          rclone --config=$HOME/rclone.conf move ftp:data upload:kdrama --transfers=1 --checkers=2 --stats=120s --verbose --dropbox-chunk-size 128m --order-by size,desc & \
          wait
          if [ $? -eq 0 ]; then
            echo "Rclone operations completed successfully."
          else
            echo "One or more Rclone operations failed!" >&2
            exit 1
          fi
