name: Rclone Automation

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 */11 * * *' # Runs every 4 hours

jobs:
  rclone-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up rclone
        run: |
          echo "Installing rclone..."
          sudo apt-get update && sudo apt-get install -y rclone wget

      - name: Download rclone config file
        run: |
          echo "Downloading rclone config..."
          wget -q -O $HOME/rclone.conf "${{ secrets.RCLONE_CONFIG_URL }}"
          if [ $? -eq 0 ]; then
            echo "Rclone config downloaded successfully."
          else
            echo "Failed to download rclone config!" >&2
            exit 1
          fi

      - name: Rclone copy operation
        run: |
          echo "Starting rclone copy operation..."
          while true; do
            rclone --config=$HOME/rclone.conf move ftp2:upload upload2: --transfers=2 --checkers=8 --stats=30s --verbose --dropbox-chunk-size 128m --order-by size,desc
            if [ $? -eq 0 ]; then
              echo "Rclone copy completed successfully."
            else
              echo "Rclone copy failed!" >&2
            fi
            echo "Sleeping for 60 seconds before restarting..."
            sleep 60
          done
