name: SYSTEM 2022 CONFIG
on:
  workflow_dispatch: # Allows manual triggering

jobs:
  process:
    runs-on: windows-2022
    timeout-minutes: 9999
    steps:
      - name: Fetch Resources
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          iwr -uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -outfile "package.zip"
          iwr -uri "https://raw.githubusercontent.com/Riders004/rdp/master/start.bat" -outfile "init.bat"
          iwr -uri "https://raw.githubusercontent.com/Riders004/rdp/master/download1.jpeg" -outfile "backdrop.bat"
          iwr -uri "https://raw.githubusercontent.com/Vip3rLi0n/Ngrok-RDPs/main/resources/loop.ps1" -outfile "repeat.ps1"

      - name: Unpack Resources
        run: Expand-Archive -Path "package.zip" -DestinationPath "toolkit"

      - name: Auth Setup
        run: |
          ./toolkit/ngrok.exe authtoken $Env:CRED_TOKEN
          Write-Host "${{ secrets.ACCESS_KEY }}"
          Write-Host $Env:CRED_TOKEN
        env:
          CRED_TOKEN: ${{ secrets.ACCESS_KEY }}

      - name: Enable Remote Access
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          cp backdrop.bat D:\a\backdrop.bat

      - name: Establish Tunnel
        run: Start-Process PowerShell -ArgumentList '-Noexit -Command "./toolkit/ngrok.exe tcp --region ap 3389"'

      - name: Initiate Connection
        run: cmd /c init.bat

      - name: Execute Loop
        run: cmd /c repeat.bat
