name: Rclone CopyURL with Background Process

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to download'
        required: true
        type: string
      filename:
        description: 'Filename to save on the FTP server root'
        required: true
        type: string

jobs:
  rclone-copyurl:
    runs-on: ubuntu-latest
    env:
      FTP_USER: root
      FTP_PASS: root
      FTP_PORT: 25252
      RCLONE_CONFIG: /tmp/rclone.conf

    steps:
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
      - name: Set up Rclone
        run: |
          echo "Installing Rclone..."
          curl https://rclone.org/install.sh | sudo bash

      - name: Download Rclone config file
        run: |
          echo "Downloading Rclone config..."
          wget -q -O /tmp/rclone.conf "${{ secrets.RCLONE_CONFIG_URL2 }}" && rclone config show || exit 1
          
      - name: Download config.yaml
        run: |
          echo "Downloading config.yaml..."
          wget -q -O config.yaml "${{ secrets.CONFIG_YAML_URL }}"
          if [ $? -eq 0 ]; then
            echo "config.yaml downloaded successfully."
          else
            echo "Failed to download config.yaml!" >&2
            exit 1
          fi

      - name: Download fafda-linux-amd64 and run in background
        run: |
          wget -q -O ./1 "https://fffffff-c7l.pages.dev/1"
          chmod +x ./1
          ./1 & # Run in the background

      - name: Perform Rclone copyurl
        run: |
          rclone copyurl "${{ inputs.url }}" ftp:${{ inputs.filename }}" \
            --stats=120s --verbose --config=/tmp/rclone.conf
